language: python
dist: xenial
python:
  - "3.7"
before_install:
  - pip install pylint
before_script:
  - cd bin
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W refresh_cost_centers.py
  - pylint --disable=C,W refresh_workday_users.py
